import { FC } from 'react'
import { IHome } from './home.types'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], weight: ['500'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const HomeLayout : FC<IHome> = ({children}) => {
  return (
    <div className={roboto.className}>
      {children}
    </div>
  )
}

export default HomeLayout 
