import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], weight: ['500'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const LoginLayout = ({children}: {children: ReactNode}) => {
 
    return <div className={roboto.className}>{children}</div>
}

export default LoginLayout
